name: ${project.name}
main: ${project.groupId}.${project.artifactId}.Main
version: ${project.version}
author: LeonTG77
description: This plugin adds a timer that will countdown in the action bar of players.

commands:
  timer:
    description: Timer command, check usaged.